app/app.Web/Controllers/AuditController.cs
using app.Service.Services;
using app.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace app.Web.Controllers
{
    [Authorize]
    [Route("audit")]
    public class AuditController : Controller
    {
        private readonly IAuditService _auditService;

        public AuditController(IAuditService auditService)
        {
            _auditService = auditService;
        }

        /// <summary>
        /// Audit index page to view all logs
        /// </summary>
        /// <returns>view with list of logs (if they exist)</returns>
        [Route("")]
        public async Task<IActionResult> Index()
        {
            var model = new AuditLogListVM();

            var logs = await _auditService.GetAllLogs();

            if (logs.Any())
            {
                model.Logs = logs.Select(l => new AuditLogVM(l)).ToList();
            }

            return View(model);
        }
    }
}

app/app.Web/Controllers/ProductController.cs
using app.Domain.Entities.Product;
using app.Service.Services;
using app.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace app.Web.Controllers
{
    [Authorize]
    [Route("products")]
    public class ProductController : Controller
    {
        private readonly IProductService _productService;

        /// <summary>
        /// Product controller constructor
        /// </summary>
        /// <param name="productService">injected product service</param>
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }

        /// <summary>
        /// Product list page
        /// </summary>
        /// <returns>products view with a list of product viewmodels</returns>
        [HttpGet("")]
        public async Task<IActionResult> Index()
        {
            var model = new ProductListVM();

            var products = await _productService.GetAllProducts();

            if (products.Any())
            {
                model.Products = products.Select(p => new ProductVM(p)).ToList();
            }

            return View(model);
        }

        /// <summary>
        /// Product details page
        /// </summary>
        /// <param name="slug">product url slug</param>
        /// <returns>details view with product details viewmodel</returns>
        [HttpGet("{slug}")]
        public async Task<IActionResult> Details(string slug)
        {
            var product = await _productService.GetProduct(slug);

            if (product == null) // if product does not exist, redirect to products page
            {
                return RedirectToAction(nameof(Index));
            }

            var model = new ProductDetailsVM(product);

            return View(model);
        }

        /// <summary>
        /// GET: product create
        /// </summary>
        /// <returns>product create page with create product form data</returns>
        [HttpGet("create")]
        public ActionResult Create()
        {
            var model = new ProductSaveVM()
            {
                ColorList = _productService.GetProductColors().Select(o => new ColorOptionVM(o)).ToList(),
            };

            return View("Save", model);
        }

        /// <summary>
        /// POST: product create
        /// </summary>
        /// <param name="vm">created product viewmodel</param>
        /// <returns>redirects to products page if successful. Returns current page if error</returns>
        [HttpPost("create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm]ProductSaveVM vm)
        {
            if (ModelState.IsValid)
            {
                var product = BuildProductDTO(vm);

                var createResult = await _productService.CreateProduct(product);

                if (createResult)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            vm.ColorList = _productService.GetProductColors().Select(o => new ColorOptionVM(o)).ToList();
            vm.Error = true; // since we made it here, flag the error and return to create page

            return View("Save", vm);
        }

        /// <summary>
        /// GET: edit product
        /// </summary>
        /// <param name="slug">url slug of product to edit</param>
        /// <returns>edit page if product exists, products page if product does not exist</returns>
        [HttpGet("edit/{slug}")]
        public async Task<IActionResult> Edit(string slug)
        {
            var product = await _productService.GetProduct(slug);

            if (product != null)
            {
                var model = new ProductSaveVM(product)
                {
                    Color = _productService.GetColorId(product.Color),
                    ColorList = _productService.GetProductColors().Select(o => new ColorOptionVM(o)).ToList(),
                };

                return View("Save", model);
            }

            return RedirectToAction(nameof(Index)); //redirect to products page if product does not exist
        }

        /// <summary>
        /// POST: edit product
        /// </summary>
        /// <param name="vm">edit product viewmodel</param>
        /// <returns>redirects to products page if successful. Returns current page if error</returns>
        [HttpPost("edit/{slug}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] ProductSaveVM vm)
        {
            if (ModelState.IsValid)
            {
                var product = BuildProductDTO(vm, true);

                var editResult = await _productService.UpdateProduct(product);

                if (editResult)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            vm.ColorList = _productService.GetProductColors().Select(o => new ColorOptionVM(o)).ToList();
            vm.Error = true; // since we made it here, flag the error and return to save page

            return View("Save", vm);
        }

        /// <summary>
        /// POST: delete product
        /// </summary>
        /// <param name="vm">deleted product vm</param>
        /// <returns>redirects to products page if successful, returns to details page if not</returns>
        [HttpPost("delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromForm] ProductDeleteVM vm)
        {
            if (ModelState.IsValid)
            {
                var deleteResult = await _productService.DeleteProduct(vm.Id);

                if (deleteResult)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return RedirectToAction("details", "product", new { slug = vm.Slug});
        }

        /// <summary>
        /// Build product DTO to be sent to the service layer -> repo layer
        /// </summary>
        /// <param name="vm">vm from create/edit page</param>
        /// <param name="edit">determines if this is a new product or existing (set on the controller)</param>
        /// <returns>product dto</returns>
        private Product BuildProductDTO(ProductSaveVM vm, bool edit = false)
        {
            var dto = new Product
            {
                Id = !edit ? 0 : vm.Id,
                Name = vm.Name,
                Color = _productService.GetColorName(vm.Color),
                Price = vm.Price,
                Slug = !edit ? Guid.NewGuid().ToString() : string.Empty //slug is never updated on an edit so setting to empty
            };

            return dto;
        }
    }
}

app/app.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Audit Logger</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Audit Logger</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="Index">Audit</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        </ul>
                    }
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Audit Logger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @*<script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>*@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>